name: tests

on: push

jobs:
  test_cpu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: install gtest
        run: git clone https://github.com/google/googletest.git && cd googletest && mkdir build && cd build && cmake .. && sudo make install
      - name: test cpu
        run: ./run_tests.sh

  test_avx:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: install gtest
        run: git clone https://github.com/google/googletest.git && cd googletest && mkdir build && cd build && cmake .. && sudo make install
      - name: test avx
        run: ./run_tests.sh -DAVX
